version: '3.9'

services:
    postgres1:
        image: postgres
        container_name: postgres_container1
        restart: on-failure
        environment: 
            - POSTGRES_DB=education_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data 

    postgres2:
        image: postgres
        container_name: postgres_container2
        restart: on-failure
        environment: 
            - POSTGRES_DB=messages_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5433:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data 

    app:
        container_name: app
        build: .
        command: sh -c "
                    python manage.py makemigrations &&
                    python manage.py migrate --database=education_db && 
                    python manage.py migrate --database=messages_db && 
                    python manage.py collectstatic --no-input && 
                    python manage.py initadmin && 
                    gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8000"
        restart: on-failure
        depends_on: 
            - postgres1
            - postgres2
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media

        
    nginx:
        container_name: nginx
        command: nginx -g 'daemon off;'
        image: nginx
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/app/media
            - ./static:/app/static


networks: 
    main:
        external: true

volumes: 
    static:
        external: true
    
    postgres_data:
        external: true
    
